config-version: 2

name: 'github'
version: '0.2.0'

require-dbt-version: [">=0.18.0", "<0.20.0"] 

models:
    github:
        materialized: table
        intermediate:
            materialized: ephemeral
 
vars:
    github:
        issue_assignee:                 "{{ ref('stg_github__issue_assignee') }}"
        issue_closed_history:           "{{ ref('stg_github__issue_closed_history') }}"
        issue_comment:                  "{{ ref('stg_github__issue_comment') }}"
        issue_label:                    "{{ ref('stg_github__issue_label') }}"
        issue_merged:                   "{{ ref('stg_github__issue_merged') }}"
        issue:                          "{{ ref('stg_github__issue') }}"
        pull_request_review:            "{{ ref('stg_github__pull_request_review') }}"
        pull_request:                   "{{ ref('stg_github__pull_request') }}"
        repository:                     "{{ ref('stg_github__repository') }}"
        requested_reviewer_history:     "{{ ref('stg_github__requested_reviewer_history') }}"
        user:                           "{{ ref('stg_github__user') }}"